lesson34/app/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/<slug:slug>/add-comment/', add_comment, name='add_comment'),

    path('product/<slug:slug>/like/', like_product, name='like_product'),
    path('comment/<int:pk>/like/', like_comment, name='like_comment'),

    path('product/<slug:slug>/dislike/', dislike_product, name='dislike_product'),
    path('comment/<int:pk>/dislike/', dislike_comment, name='dislike_comment'),

    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),

    path('profile/', UserProfileView.as_view(), name='profile'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/remove/<slug:slug>/', remove_from_cart, name='remove_from_cart'),
    path('cart/buy/', buy_products, name='buy'),
    path('cart/buy-history/', BuyHistoryListView.as_view(), name='buy_history'),

    path('add_product/<int:product_id>/', add_product, name='add_product'),
]



lesson34/lesson34/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

lesson34/app/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Like(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('content_type', 'object_id', 'user')

    def __str__(self):
        return f"{self.content_type} - {self.object_id}"


class Dislike(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('content_type', 'object_id', 'user')

    def __str__(self):
        return f"{self.content_type} - {self.object_id}"


class Product(models.Model):
    title = models.CharField(max_length=255)
    categories = models.ManyToManyField(Category)
    price = models.PositiveIntegerField()
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField()
    likes = GenericRelation(Like)
    dislikes = GenericRelation(Dislike)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return f"{self.title} - {self.price}"

    def get_absolute_url(self):
        return reverse('remove_from_cart', args=(self.slug,))

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        str_ = f"{self.title}-{self.price}"
        self.slug = slugify(str_)
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                null=True, blank=True)
    product_list = models.ManyToManyField(Product)

    def get_total_price(self):
        return self.product_list.all().aggregate(Sum('price'))

    def __str__(self):
        if not self.user:
            return 'empty_user'
        return self.user.username


class BuyHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    product_list = models.ManyToManyField(Product)
    buy_datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    published = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    likes = GenericRelation(Like)
    dislikes = GenericRelation(Dislike)

    def __str__(self):
        return f"{self.user.username} - {self.product.title}"

lesson34/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div style="position: fixed;
                top: 0px;
                width: 100%;
                justify-content: space-between;
                margin: auto;">
        <span>{{ user.username }}</span>
        <a href="{% url 'product_list' %}">Products</a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Logout</a>
            <a href="{% url 'profile' %}">Profile</a>
            <a href="{% url 'cart' %}">Cart</a>
            <a href="{% url 'buy_history' %}">Buy history</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
    </div>

    <div style="width: 300px;
                margin: auto;
                margin-top: 50px;">
    {% block content %}
    {% endblock content %}
    </div>

</body>
</html>

lesson34/app/templates/app/buy_history.html
{% extends 'app/base.html' %}

{% block content %}

    {% for buy in history_list %}
        <p>{{ buy.user.username }} - {{ buy.buy_datetime }}</p>
        <ul>
            {% for product in buy.product_list.all %}
                <li>{{ product }}</li>
            {% endfor %}
        </ul>
    {% endfor %}

{% endblock content %}


lesson34/app/templates/app/cart.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>Cart for {{ user.username }}</h1>

    {% for product in product_list %}
        <p>{{ product }}</p>
        <p><a href="{% url 'remove_from_cart' product.slug %}">Remove from cart</a></p>
    {% endfor %}


    <p><a href="{% url 'buy' %}">Buy</a></p>


{% endblock content %}


lesson34/app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>

{% endblock content %}


lesson34/app/templates/app/product_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>Product {{ product.title }}</h1>
    {% for category in product.categories.all %}
        <span>{{ category }}, </span>
    {% endfor %}
    <p>Price - {{ product.price }}</p>
    <p>Description - {{ product.description }}</p>
    <br><br>

    {% if user.is_authenticated %}
    <form action="{% url 'add_comment' product.slug %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>
    {% endif %}

    <br>
    <h2>Comments</h2>
    {% for comment in comment_list %}
        <p>{{ comment.user.username }} - {{ comment.published }}</p>
        <p>{{ comment.body }}</p>
        <p> {{ comment.likes.count }} likes </p>
        <p> {{ comment.dislikes.count }} dislikes </p>
        <form action="{% url 'like_comment' comment.pk %}">
            <input type="submit" value="Like">
        </form>
        <form action="{% url 'dislike_comment' comment.pk %}">
            <input type="submit" value="Dislike">
        </form>
        <br>
    {% endfor %}

{% endblock content %}


lesson34/app/templates/app/product_list.html
{% extends 'app/base.html' %}

{% block content %}
    {% for product in product_list %}
        <p>{{ product }}</p>
        <p>{{ product.likes.count }} likes </p>
        <p>{{ product.dislikes.count }} dislikes </p>
        <form action="{% url 'like_product' product.slug %}">
            <input type="submit" value="Like">
        </form>
        <form action="{% url 'dislike_product' product.slug %}">
            <input type="submit" value="Dislike">
        </form>
        <p><a href="{% url 'add_product' product.id %}">Добавить в корзину</a></p>
        <p><a href="{% url 'product_detail' product.slug %}">Detail</a></p>

        <br>
    {% endfor %}
{% endblock content %}


lesson34/app/templates/app/profile.html
{% extends 'app/base.html' %}

{% block content %}
    <h1>Profile page for {{ user.username }}</h1>
{% endblock content %}


lesson34/app/templates/app/register.html
{% extends 'app/base.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>

{% endblock content %}
